### ISSUE TITLE
ixnetwork-restpy 1.1.5 with IxNetwork 9.20 error with InstanceId is not a string for field stack operation

### ISSUE THREAD

**Issue by johcheun** [OpenIxia/IxNetwork#133]
Upgraded from ixnewetork-restpy 1.0.48 to 1.1.5. 
Same script worked on IxNetwork 9.20 with 1.0.48 but not 1.1.5.

  File "/usr/local/lib/python3.7/site-packages/ixnetwork_restpy/connection.py", line 461, in _process_response_status_code                                                               
    raise BadRequestError(message, response.status_code)                                                                                                                                 
ixnetwork_restpy.errors.BadRequestError: InstanceId is not a string           

See below traceback:
======================================================================                                                                                                                   
Traceback (most recent call last):                                                                                                                                                       
  File "./submodules/p4-tests/internal_p4_16/tm_tests/tm_uc_test_pam4.py", line 238, in runTest                                                                                          
    dmac="00:00:00:55:55:55")                                                                                                                                                            
  File "/home/admin12/john/p4f-master-20220523/install/lib/python3.7/site-packages/p4testutils/TrafficGen.py", line 494, in add_ethernet                                                 
    dmac_value_type = dmac_value_type)                                                                                                                                                   
  File "/home/admin12/john/p4f-master-20220523/install/lib/python3.7/site-packages/p4testutils/TrafficGen.py", line 453, in _add_ethernet                                                
    ethernetDstField.ValueType = dmac_value_type                                                                                                                                         
  File "/usr/local/lib/python3.7/site-packages/ixnetwork_restpy/testplatform/sessions/ixnetwork/traffic/trafficitem/configelement/stack/field/field.py", line 618, in ValueType          
    self._set_attribute(self._SDM_ATT_MAP["ValueType"], value)                                                                                                                           
  File "/usr/local/lib/python3.7/site-packages/ixnetwork_restpy/base.py", line 238, in _set_attribute                                                                                    
    raise e                                                                                                                                                                              
  File "/usr/local/lib/python3.7/site-packages/ixnetwork_restpy/base.py", line 235, in _set_attribute                                                                                    
    self._update({name: value})                                                                                                                                                          
  File "/usr/local/lib/python3.7/site-packages/ixnetwork_restpy/base.py", line 425, in _update                                                                                           
    self._connection._update(href, payload)                                                                                                                                              
  File "/usr/local/lib/python3.7/site-packages/ixnetwork_restpy/connection.py", line 272, in _update                                                                                     
    return self._send_recv("PATCH", url, payload)                                                                                                                                        
  File "/usr/local/lib/python3.7/site-packages/ixnetwork_restpy/connection.py", line 575, in _send_recv                                                                                  
    self._process_response_status_code(url, headers, response)                                                                                                                           
  File "/usr/local/lib/python3.7/site-packages/ixnetwork_restpy/connection.py", line 461, in _process_response_status_code                                                               
    raise BadRequestError(message, response.status_code)                                                                                                                                 
ixnetwork_restpy.errors.BadRequestError: InstanceId is not a string                                                                                                                      
System.Exception: InstanceId is not a string                                                                                                                                             
   at SDMCsLib.SDMObjIdPiece.GetIdAsString()                                                                                                                                             
   at IxNetwork.Traffic2.Publishers.StackFieldHandler.Find(EnterExitSingleObjectHandler_EnterArgs args)                                                                                  
   at SDMHelpers.WalkContext.walkTo(SDMObjId objid, Hashtable idMapResponse, EnterReason reason)                                                                                         
   at SDMHelpers.SimplePublisher.Commit(ArrayList commitDeltasRequest, Hashtable idMapResponse, ArrayList commitMessages, SDMSandbox track)                                              
   at SDMCsLib.SDMPeer.commitPiece(ArrayList deltasForPublisher, Hashtable idMapResponse, ArrayList commitExceptionsResponse, Version version, Boolean bCommitIfUnique)                  
   at SDMCsLib.SDMPeer.SANDBOX_DoCommit(Int32 eventMatch, ArrayList commitDeltasRequest, Hashtable idMapResponse, ArrayList commitExceptionsResponse, Version version, Boolean bCommitIfU
nique, eSandboxType sandboxType)                                                                                                                                                         
   at SDMCsLib.SDMSandbox.DoCommit(Boolean bCommitIfUnique, eSandboxType sandboxType)                                                                                                    
   at SDMCsLib.SDMSandbox.Commit()                                                                                                                                                       
   at SDMCsLib.RestService.SdmSandbox.Commit(Boolean isAddOperation)                                                                                                                     
   at SDMCsLib.RestService.SdmObject.Patch()                                                                                                                                             
   at SDMCsLib.RestService.V1ObjectController.Patch(String path)                                                                                                                         
        Current Server Errors/Warnings:                                                                                                                                                  
        05/24/2022 09:32:25 [WARNING] [Traffic Generate required] The Traffic Item was modified. Please perform a Traffic Generate to update the associated traffic Flow Groups          
                                                                                                                                                                                         
----------------------------------------------------------------------

**Comment by johcheun** [comment]
@therkong  Looks like above link is now access restricted.  Also since our ixNetwork API server machine is running in native IxOS, and in kvm qcow2 environment, where both are Linux based.   How to apply above HotFix as it's Windows format .exe ?  Thanks!

**Comment by therkong** [comment]
What is your ixNetwork activation code?   Can you send email to support.ix@keysight.com and cc theresa.kong@keysight.com with problem description?
I will open a support ticket and get you the HF that you need for Linux OS
