### ISSUE TITLE
ixnetwork_restpy.errors.ConnectionError: Unable to connect to xxx.xxx.xxx.xxx. Check the ip address and consider the rest_port parameter.

### ISSUE THREAD

**Issue by filip-nikolic** [OpenIxia/IxNetwork#148]
Dear,
All

I have to share one issue with you and I believe that you can help me.

I created a small script of port reservation in Python (I am using visual studio) so I can check connectivity between my device and remote instance where is Client installed.
SO I am trying to reach from my lap top toward Windows client API that is installed on VM. 

This is the script when I want to run:

import sys, os, time, traceback

from ixnetwork_restpy import *
from ixnetwork_restpy.connection import Connection

apiServerIp = '172.20.68.9'

ixChassisIpList = ['172.30.20.132']
portList = [[ixChassisIpList[0], 1,1], [ixChassisIpList[0], 1, 2]]

forceTakePortOwnership = True

session = SessionAssistant( IpAddress=apiServerIp,  RestPort=11009, SessionId=1, LogLevel=Connection.TRACE_INFO, ClearConfig=True, VerifyCertificates=False)

ixNetwork = session.Ixnetwork
   
ixNetwork.info('Assign ports')
portMap = session.PortMapAssistant()
vport = dict()
for index,port in enumerate(portList):
        portName = 'Port_{}'.format(index+1)
        vport[portName] = portMap.Map(IpAddress=port[0], CardId=port[1], PortId=port[2], Name=portName)

portMap.Connect(forceTakePortOwnership)

When I run in debug mode I am getting:
![image](https://github.com/user-attachments/assets/4fb77838-7e1a-45c2-8ebd-4501660593bf)

And this is output from debug mode:

PS D:\ORAN&OOPT\BNG\IxIA>  d:; cd 'd:\ORAN&OOPT\BNG\IxIA'; & 'c:\Users\filip.m.nikolic\AppData\Local\Programs\Python\Python311\python.exe' 'c:\Users\filip.m.nikolic\.vscode\extensions\ms-python.debugpy-2024.10.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher' '52786' '--' 'D:\ORAN&OOPT\BNG\IxIA\Test1.py' 
4\x5cbundled\x5clibs\x5cdebugpy\x5cadapter/../..\x5cdebugpy\x5clauncher' '52786' '--' 'D:\x5cORAN&OOPT\x5cBNG\x5cIxIA\x5cTest1.py' ;f0afe1ae-62cb-4ad9-ac8e-d6f98f3eb0122024-10-09 08:34:17 [ixnetwork_restpy.connection tid:16652] [INFO] using python version 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]
2024-10-09 08:34:17 [ixnetwork_restpy.connection tid:16652] [INFO] using ixnetwork-restpy version 1.4.0
2024-10-09 08:34:17 [ixnetwork_restpy.connection tid:16652] [WARNING] Verification of certificates is disabled
2024-10-09 08:34:17 [ixnetwork_restpy.connection tid:16652] [INFO] Determining the platform and rest_port using the 172.20.68.9 address...
2024-10-09 08:34:18 [ixnetwork_restpy.connection tid:16652] [WARNING] Unable to connect to http://172.20.68.9:11009.
2024-10-09 08:34:18 [ixnetwork_restpy.connection tid:16652] [WARNING] Unable to connect to https://172.20.68.9:11009.
2024-10-09 08:34:20 [ixnetwork_restpy.connection tid:16652] [WARNING] Unable to connect to http://172.20.68.9:443.
2024-10-09 08:34:22 [ixnetwork_restpy.connection tid:16652] [WARNING] Unable to connect to https://172.20.68.9:443.
Traceback (most recent call last):
  File "c:\Users\filip.m.nikolic\AppData\Local\Programs\Python\Python311\Lib\runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\filip.m.nikolic\AppData\Local\Programs\Python\Python311\Lib\runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "c:\Users\filip.m.nikolic\.vscode\extensions\ms-python.debugpy-2024.10.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy\__main__.py", line 39, in <module>    cli.main()
  File "c:\Users\filip.m.nikolic\.vscode\extensions\ms-python.debugpy-2024.10.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
  File "c:\Users\filip.m.nikolic\.vscode\extensions\ms-python.debugpy-2024.10.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "c:\Users\filip.m.nikolic\.vscode\extensions\ms-python.debugpy-2024.10.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 321, in run_path        
    return _run_module_code(code, init_globals, run_name,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\filip.m.nikolic\.vscode\extensions\ms-python.debugpy-2024.10.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 135, in _run_module_code    _run_code(code, mod_globals, init_globals,
  File "c:\Users\filip.m.nikolic\.vscode\extensions\ms-python.debugpy-2024.10.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 124, in _run_code       
    exec(code, run_globals)
  File "D:\ORAN&OOPT\BNG\IxIA\Test1.py", line 14, in <module>
    session = SessionAssistant( IpAddress=apiServerIp,  RestPort=11009, SessionId=1, LogLevel=Connection.TRACE_INFO, ClearConfig=True, VerifyCertificates=False)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\filip.m.nikolic\AppData\Local\Programs\Python\Python311\Lib\site-packages\ixnetwork_restpy\assistants\sessions\sessionassistant.py", line 84, in __init__
    testplatform = TestPlatform(
                   ^^^^^^^^^^^^^
  File "c:\Users\filip.m.nikolic\AppData\Local\Programs\Python\Python311\Lib\site-packages\ixnetwork_restpy\testplatform\testplatform.py", line 80, in __init__
    self._connection = Connection(
                       ^^^^^^^^^^^
  File "c:\Users\filip.m.nikolic\AppData\Local\Programs\Python\Python311\Lib\site-packages\ixnetwork_restpy\connection.py", line 147, in __init__
    self._scheme = self._determine_test_tool_platform(platform)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\filip.m.nikolic\AppData\Local\Programs\Python\Python311\Lib\site-packages\ixnetwork_restpy\connection.py", line 216, in _determine_test_tool_platform
    raise ConnectionError(
ixnetwork_restpy.errors.ConnectionError: Unable to connect to 172.20.68.9. Check the ip address and consider the rest_port parameter.
PS D:\ORAN&OOPT\BNG\IxIA> 

Can you please suggest me what I am doing wrong?

Thanks in advance,
Filip

**Comment by hubogee** [comment]
For support issues, please send an email to support.ix@keysight.com.  Someone will be with you shortly.  Thanks.
