### ISSUE TITLE
RestPy:Cannot modify or add OspfRouteProperty

### ISSUE THREAD

**Issue by muthvar1** [OpenIxia/IxNetwork#37]
Whenever I try to add or change a property in this default added OspfRouteProperty under Network Group, the restPy module errors out on me. Looks like some modules maybe missing in restPy

networkGroup1.OspfRouteProperty.routeOrigin.Single(

Traceback (most recent call last):
  File "/opt/cisco/aci/python2.7/bin/bpython", line 9, in <module>
    load_entry_point('bpython==0.12', 'console_scripts', 'bpython')()
  File "/opt/cisco/aci/python2.7/lib/python2.7/site-packages/bpython/cli.py", line 1918, in main
    banner=banner)
  File "/opt/cisco/aci/python2.7/lib/python2.7/site-packages/bpython/cli.py", line 1815, in curses_wrapper
    return func(stdscr, *args, **kwargs)
  File "/opt/cisco/aci/python2.7/lib/python2.7/site-packages/bpython/cli.py", line 1888, in main_curses
    exit_value = clirepl.repl()
  File "/opt/cisco/aci/python2.7/lib/python2.7/site-packages/bpython/cli.py", line 1116, in repl
    inp = self.get_line()
  File "/opt/cisco/aci/python2.7/lib/python2.7/site-packages/bpython/cli.py", line 673, in get_line
    if self.p_key(key) is None:
  File "/opt/cisco/aci/python2.7/lib/python2.7/site-packages/bpython/cli.py", line 1011, in p_key
    self.addstr(key)
  File "/opt/cisco/aci/python2.7/lib/python2.7/site-packages/bpython/cli.py", line 348, in addstr
    self.complete()
  File "/opt/cisco/aci/python2.7/lib/python2.7/site-packages/bpython/cli.py", line 445, in complete
    self.list_win_visible = repl.Repl.complete(self, tab)
  File "/opt/cisco/aci/python2.7/lib/python2.7/site-packages/bpython/repl.py", line 546, in complete
    if not self.get_args():
  File "/opt/cisco/aci/python2.7/lib/python2.7/site-packages/bpython/repl.py", line 505, in get_args
    f = self.get_object(func)
  File "/opt/cisco/aci/python2.7/lib/python2.7/site-packages/bpython/repl.py", line 451, in get_object
    obj = getattr(obj, attributes.pop(0))
  File "/local/vamuthal/Ixia_RestPy/RestPy/ixnetwork_restpy/testplatform/sessions/ixnetwork/topology/ospfrouteproperty.py", line 297, in RouteOrigin
    return self._get_attribute('routeOrigin')
  File "/local/vamuthal/Ixia_RestPy/RestPy/ixnetwork_restpy/base.py", line 122, in _get_attribute
    raise NotFoundError('The attribute %s is not in the internal list of object dicts. (%s)' % (name, e))
ixnetwork_restpy.errors.NotFoundError: The attribute routeOrigin is not in the internal list of object dicts. (list index out of range)

**Comment by hubertgee** [comment]
I saw two misunderstandings that should resolve your issue.
 
1>	You were using the wrong object.  You should be using the ipv4PrefixPool object instead of networkGroup1.  I created an OSPF config in my setup.  To verify your issue, I used RestPy to do a find() for the Ipv4PrefixPools object first since I did not use a script to create my ospf config from scratch.  Then by using the Ipv4PrefixPools object, I could now get to the OspfRouteProperty object to set the RouteOrigin.
 
    ospfRouteProperty = ixNetwork.Topology.find(Name='Topo1').DeviceGroup.find()[0].NetworkGroup.find()[0].Ipv4PrefixPools.find()[0].OspfRouteProperty.find()[0]
    ospfRouteProperty.RouteOrigin.Single('samearea')
 
2>	All child methods and parameter arguments always begin with an uppercase.  So in your syntax, your routeOrigin needs to begin with uppercase “RouteOrigin”.
 
In the future when troubleshooting something like this, take the time to make your configuration on the GUI and verify on the API browser for the endpoint object to use.
The API Browser is your best tool.
 
Hubert Gee
