### ISSUE TITLE
getMultivalueValues fails, while startAllProtocols(verifyDeviceGroupStatus)

### ISSUE THREAD

**Issue by chen-charles** [OpenIxia/IxNetwork#4]
```python3
Traceback (most recent call last):
  File "addPacketHeaderRawTraffic.py", line 169, in <module>
    protocolObj.startAllProtocols()
  File "../Modules/IxNetRestApiProtocol.py", line 1222, in startAllProtocols
    self.verifyDeviceGroupStatus()
  File "../Modules/IxNetRestApiProtocol.py", line 1178, in verifyDeviceGroupStatus
    enabled = self.ixnObj.getMultivalueValues(enabledMultivalue, silentMode=True)
  File "../Modules/IxNetRestApi.py", line 998, in getMultivalueValues
    response = self.post(self.sessionUrl+'/multivalue/operations/getValues', data=data, silentMode=silentMode)
  File "../Modules/IxNetRestApi.py", line 291, in post
    raise IxNetRestApiException('POST error: {0}\n'.format(response.json()['errors'][0]['detail']))
IxNetRestApi.IxNetRestApiException: POST error: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
```

while attempting to fetch
```python3
    'enabled': '/api/v1/sessions/1/ixnetwork/multivalue/23',    # count = 1 returned by query
```

Currently bypassed by,
```python3
    def getMultivalueValues(self, multivalueObj, silentMode=False):
        return self.get(self.httpHeader+multivalueObj+'?includes=values', silentMode=silentMode).json()["values"]
```

IxNetwork Version: 8.10.1046.6 EA
Could not find "getValues" exec in the API Browser (nor docs). (only "/multivalue/operations/getValue")

**Comment by hubertgee** [comment]
Hi Charles, the multivalue/operations/getValue feature isn't supported in IxNetwork 8.10.  I suggest upgrading to IxNetwork 8.40.
